//Standard basic libraries
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <boost/multiprecision/cpp_int.hpp>
#include <cmath>
//Mapping of canonical names to registers
#include "program_structure/Rregdict.cpp"

using namespace boost::multiprecision;

//Utility programs which facilitate in computing the outputs
#include "utility programs/str2bin.cpp"
#include "utility programs/bindec.cpp"
#include "utility programs/usgnbindec.cpp"
#include "utility programs/bitlogic.cpp"
#include "utility programs/printreg.cpp"
#include "utility programs/Mem.cpp"
#include "utility programs/printmem.cpp"
#include "utility programs/binhex.cpp"
#include "utility programs/fileprintmem.cpp"
#include "utility programs/fileprintreg.cpp"
#include "Floating_Point_Instructions/Miscellaneous/Converter.cpp"
#include "Floating_Point_Instructions/Miscellaneous/getrounding.cpp"

//Programs associated with each opcode
#include "arithmetic instructions/lui.cpp"
#include "arithmetic instructions/auipc.cpp"
#include "arithmetic instructions/addi.cpp"
#include "arithmetic instructions/slti.cpp"
#include "arithmetic instructions/sltiu.cpp"
#include "arithmetic instructions/xori.cpp"
#include "arithmetic instructions/ori.cpp"
#include "arithmetic instructions/andi.cpp"
#include "arithmetic instructions/slli.cpp"
#include "arithmetic instructions/srli.cpp"
#include "arithmetic instructions/srai.cpp"
#include "arithmetic instructions/add.cpp"
#include "arithmetic instructions/sub.cpp"
#include "arithmetic instructions/slt.cpp"
#include "arithmetic instructions/sltu.cpp"
#include "arithmetic instructions/sll.cpp"
#include "arithmetic instructions/srl.cpp"
#include "arithmetic instructions/sra.cpp"
#include "arithmetic instructions/xor.cpp"
#include "arithmetic instructions/and.cpp"
#include "arithmetic instructions/or.cpp"
#include "arithmetic instructions/addiw.cpp"
#include "arithmetic instructions/slliw.cpp"
#include "arithmetic instructions/srliw.cpp"
#include "arithmetic instructions/sraiw.cpp"
#include "arithmetic instructions/sllw.cpp"
#include "arithmetic instructions/srlw.cpp"
#include "arithmetic instructions/sraw.cpp"
#include "arithmetic instructions/addw.cpp"
#include "arithmetic instructions/subw.cpp"
#include "arithmetic instructions/divs.cpp"
#include "arithmetic instructions/divu.cpp"
#include "arithmetic instructions/divw.cpp"
#include "arithmetic instructions/rem.cpp"
#include "arithmetic instructions/remu.cpp"
#include "mul instructions/mul.cpp"
#include "mul instructions/mulh.cpp"
#include "mul instructions/mulhu.cpp"
#include "mul instructions/mulhsu.cpp"
#include "mul instructions/mulw.cpp"
#include "memory instructions/lb.cpp"
#include "memory instructions/lh.cpp"
#include "memory instructions/lhu.cpp"
#include "memory instructions/lbu.cpp"
#include "memory instructions/lwu.cpp"
#include "memory instructions/lw.cpp"
#include "memory instructions/ld.cpp"
#include "memory instructions/sb.cpp"
#include "memory instructions/sh.cpp"
#include "memory instructions/sw.cpp"
#include "memory instructions/sd.cpp"
#include "branch instructions/jal.cpp"
#include "branch instructions/jalr.cpp"
#include "branch instructions/beq.cpp"
#include "branch instructions/blt.cpp"
#include "branch instructions/bge.cpp"
#include "branch instructions/bltu.cpp"
#include "branch instructions/bgeu.cpp"
#include "branch instructions/bne.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FADD.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FDIV.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FMADD.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FMAX.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FMIN.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FMSUB.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FMUL.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FNMADD.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FNMSUB.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FSQRT.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Arithmetic/FSUB.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Classify/FCLASS.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Compare/FEQ.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Compare/FLE.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Compare/FLT.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.L.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.LU.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.S.L.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.SU.L.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.SU.W.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.S.W.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.W.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FCVT.WU.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FMV.S.X.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FMV.X.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FSGNJN.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FSGNJ.S.cpp"
#include "Floating_Point_Instructions/SP_Instructions/Conversion_and_Move/FSGNJX.S.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FADD.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FDIV.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FMADD.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FMAX.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FMIN.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FMSUB.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FMUL.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FNMADD.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FNMSUB.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FSQRT.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Arithmetic/FSUB.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Classify/FCLASS.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Compare/FEQ.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Compare/FLE.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Compare/FLT.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.L.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.LU.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.D.L.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.DU.L.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.DU.W.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.D.W.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.W.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FCVT.WU.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FMV.D.X.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FMV.X.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FSGNJN.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FSGNJ.D.cpp"
#include "Floating_Point_Instructions/DP_Instructions/Conversion_and_Move/FSGNJX.D.cpp"





