create_clock -add -name CLK -period 10.0 -waveform {0 5.0} [get_ports CLK]                                                                                                                                   
set_property PACKAGE_PIN E3 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN U9 [get_ports RST_N]
set_property IOSTANDARD LVCMOS33 [get_ports RST_N]
set_property PACKAGE_PIN C4 [get_ports sin_in]
set_property IOSTANDARD LVCMOS33 [get_ports sin_in]
set_property PACKAGE_PIN D4 [get_ports sout]
set_property IOSTANDARD LVCMOS33 [get_ports sout]