//
// Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
//
// On Tue Sep 29 16:31:46 IST 2015
//
//
// Ports:
// Name                         I/O  size props
// c_z_mux                        O     2
// c_z_mux_fp                     I     1
// c_z_mux_fm                     I     1
// c_z_mux_cp                     I     1
//
// Combinational paths from inputs to outputs:
//   (c_z_mux_fp, c_z_mux_fm, c_z_mux_cp) -> c_z_mux
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_c_z_mux(c_z_mux_fp,
		      c_z_mux_fm,
		      c_z_mux_cp,
		      c_z_mux);
  // value method c_z_mux
  input  c_z_mux_fp;
  input  c_z_mux_fm;
  input  c_z_mux_cp;
  output [1 : 0] c_z_mux;

  // signals for module outputs
  wire [1 : 0] c_z_mux;

  // remaining internal signals
  wire [1 : 0] res__h25, res__h27;
  wire x__h22;

  // value method c_z_mux
  assign c_z_mux = c_z_mux_cp ? res__h25 : res__h27 ;

  // remaining internal signals
  assign res__h25 = { x__h22, ~c_z_mux_fm } ;
  assign res__h27 = { ~x__h22, c_z_mux_fp } ;
  assign x__h22 = c_z_mux_fp | c_z_mux_fm ;
endmodule  // module_c_z_mux

