//
// Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
//
// On Tue Sep 29 16:31:51 IST 2015
//
//
// Ports:
// Name                         I/O  size props
// wallace_rba                    O   256
// wallace_rba_inp                I  2048
//
// Combinational paths from inputs to outputs:
//   wallace_rba_inp -> wallace_rba
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_wallace_rba(wallace_rba_inp,
			  wallace_rba);
  // value method wallace_rba
  input  [2047 : 0] wallace_rba_inp;
  output [255 : 0] wallace_rba;

  // signals for module outputs
  wire [255 : 0] wallace_rba;

  // remaining internal signals
  wire [255 : 0] rbAdder___d12,
		 rbAdder___d15,
		 rbAdder___d22,
		 rbAdder___d29,
		 rbAdder___d32,
		 rbAdder___d5;
  wire [127 : 0] s1_1m__h19,
		 s1_1p__h20,
		 s1_2m__h25,
		 s1_2p__h26,
		 s1_3m__h34,
		 s1_3p__h35,
		 s1_4m__h37,
		 s1_4p__h38,
		 s2_1m__h42,
		 s2_1p__h43,
		 s2_2m__h49,
		 s2_2p__h50;

  // value method wallace_rba
  module_rbAdder instance_rbAdder_6(.rbAdder_ap(s2_1p__h43),
				    .rbAdder_am(s2_1m__h42),
				    .rbAdder_bp(s2_2p__h50),
				    .rbAdder_bm(s2_2m__h49),
				    .rbAdder(wallace_rba));

  // remaining internal signals
  module_rbAdder instance_rbAdder_1(.rbAdder_ap(wallace_rba_inp[127:0]),
				    .rbAdder_am(wallace_rba_inp[255:128]),
				    .rbAdder_bp(wallace_rba_inp[383:256]),
				    .rbAdder_bm(wallace_rba_inp[511:384]),
				    .rbAdder(rbAdder___d5));
  module_rbAdder instance_rbAdder_0(.rbAdder_ap(wallace_rba_inp[639:512]),
				    .rbAdder_am(wallace_rba_inp[767:640]),
				    .rbAdder_bp(wallace_rba_inp[895:768]),
				    .rbAdder_bm(wallace_rba_inp[1023:896]),
				    .rbAdder(rbAdder___d12));
  module_rbAdder instance_rbAdder_2(.rbAdder_ap(s1_1p__h20),
				    .rbAdder_am(s1_1m__h19),
				    .rbAdder_bp(s1_2p__h26),
				    .rbAdder_bm(s1_2m__h25),
				    .rbAdder(rbAdder___d15));
  module_rbAdder instance_rbAdder_3(.rbAdder_ap(wallace_rba_inp[1151:1024]),
				    .rbAdder_am(wallace_rba_inp[1279:1152]),
				    .rbAdder_bp(wallace_rba_inp[1407:1280]),
				    .rbAdder_bm(wallace_rba_inp[1535:1408]),
				    .rbAdder(rbAdder___d22));
  module_rbAdder instance_rbAdder_4(.rbAdder_ap(wallace_rba_inp[1663:1536]),
				    .rbAdder_am(wallace_rba_inp[1791:1664]),
				    .rbAdder_bp(wallace_rba_inp[1919:1792]),
				    .rbAdder_bm(wallace_rba_inp[2047:1920]),
				    .rbAdder(rbAdder___d29));
  module_rbAdder instance_rbAdder_5(.rbAdder_ap(s1_3p__h35),
				    .rbAdder_am(s1_3m__h34),
				    .rbAdder_bp(s1_4p__h38),
				    .rbAdder_bm(s1_4m__h37),
				    .rbAdder(rbAdder___d32));
  assign s1_1m__h19 = rbAdder___d5[127:0] ;
  assign s1_1p__h20 = rbAdder___d5[255:128] ;
  assign s1_2m__h25 = rbAdder___d12[127:0] ;
  assign s1_2p__h26 = rbAdder___d12[255:128] ;
  assign s1_3m__h34 = rbAdder___d22[127:0] ;
  assign s1_3p__h35 = rbAdder___d22[255:128] ;
  assign s1_4m__h37 = rbAdder___d29[127:0] ;
  assign s1_4p__h38 = rbAdder___d29[255:128] ;
  assign s2_1m__h42 = rbAdder___d15[127:0] ;
  assign s2_1p__h43 = rbAdder___d15[255:128] ;
  assign s2_2m__h49 = rbAdder___d32[127:0] ;
  assign s2_2p__h50 = rbAdder___d32[255:128] ;
endmodule  // module_wallace_rba

