//
// Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
//
// On Mon Sep 14 23:06:22 IST 2015
//
//
// Ports:
// Name                         I/O  size props
// priority_encoder               O     4
// priority_encoder_inp           I     4
// priority_encoder_alu_free      I     1
//
// Combinational paths from inputs to outputs:
//   (priority_encoder_inp, priority_encoder_alu_free) -> priority_encoder
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_priority_encoder(priority_encoder_inp,
			       priority_encoder_alu_free,
			       priority_encoder);
  // value method priority_encoder
  input  [3 : 0] priority_encoder_inp;
  input  priority_encoder_alu_free;
  output [3 : 0] priority_encoder;

  // signals for module outputs
  wire [3 : 0] priority_encoder;

  // value method priority_encoder
  assign priority_encoder =
	     priority_encoder_alu_free ?
	       (priority_encoder_inp[0] ?
		  4'd1 :
		  (priority_encoder_inp[1] ?
		     4'd2 :
		     (priority_encoder_inp[2] ?
			4'd4 :
			(priority_encoder_inp[3] ? 4'd8 : 4'd0)))) :
	       4'd0 ;
endmodule  // module_priority_encoder

