//
// Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
//
// On Fri Jan 22 01:17:47 IST 2016
//
//
// Ports:
// Name                         I/O  size props
// rb_nb3                         O    49
// rb_nb3_rb                      I   128
// rb_nb3_fwd                     I    33
//
// Combinational paths from inputs to outputs:
//   (rb_nb3_rb, rb_nb3_fwd) -> rb_nb3
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_rb_nb3(rb_nb3_rb,
		     rb_nb3_fwd,
		     rb_nb3);
  // value method rb_nb3
  input  [127 : 0] rb_nb3_rb;
  input  [32 : 0] rb_nb3_fwd;
  output [48 : 0] rb_nb3;

  // signals for module outputs
  wire [48 : 0] rb_nb3;

  // remaining internal signals
  wire [47 : 0] _theResult___fst__h24;
  wire [1 : 0] c_z_mux___d34,
	       c_z_mux___d36,
	       c_z_mux___d38,
	       c_z_mux___d40,
	       c_z_mux___d42,
	       c_z_mux___d44,
	       c_z_mux___d46,
	       c_z_mux___d48,
	       c_z_mux___d50,
	       c_z_mux___d52,
	       c_z_mux___d54,
	       c_z_mux___d56,
	       c_z_mux___d58,
	       c_z_mux___d60,
	       c_z_mux___d62,
	       c_z_mux___d64;

  // value method rb_nb3
  assign rb_nb3 = { _theResult___fst__h24, c_z_mux___d64[0] } ;

  // remaining internal signals
  module_c_z_mux instance_c_z_mux_1(.c_z_mux_fp(rb_nb3_rb[96]),
				    .c_z_mux_fm(rb_nb3_rb[32]),
				    .c_z_mux_cp(rb_nb3_fwd[0]),
				    .c_z_mux(c_z_mux___d34));
  module_c_z_mux instance_c_z_mux_0(.c_z_mux_fp(rb_nb3_rb[97]),
				    .c_z_mux_fm(rb_nb3_rb[33]),
				    .c_z_mux_cp(c_z_mux___d34[0]),
				    .c_z_mux(c_z_mux___d36));
  module_c_z_mux instance_c_z_mux_2(.c_z_mux_fp(rb_nb3_rb[98]),
				    .c_z_mux_fm(rb_nb3_rb[34]),
				    .c_z_mux_cp(c_z_mux___d36[0]),
				    .c_z_mux(c_z_mux___d38));
  module_c_z_mux instance_c_z_mux_3(.c_z_mux_fp(rb_nb3_rb[99]),
				    .c_z_mux_fm(rb_nb3_rb[35]),
				    .c_z_mux_cp(c_z_mux___d38[0]),
				    .c_z_mux(c_z_mux___d40));
  module_c_z_mux instance_c_z_mux_4(.c_z_mux_fp(rb_nb3_rb[100]),
				    .c_z_mux_fm(rb_nb3_rb[36]),
				    .c_z_mux_cp(c_z_mux___d40[0]),
				    .c_z_mux(c_z_mux___d42));
  module_c_z_mux instance_c_z_mux_5(.c_z_mux_fp(rb_nb3_rb[101]),
				    .c_z_mux_fm(rb_nb3_rb[37]),
				    .c_z_mux_cp(c_z_mux___d42[0]),
				    .c_z_mux(c_z_mux___d44));
  module_c_z_mux instance_c_z_mux_6(.c_z_mux_fp(rb_nb3_rb[102]),
				    .c_z_mux_fm(rb_nb3_rb[38]),
				    .c_z_mux_cp(c_z_mux___d44[0]),
				    .c_z_mux(c_z_mux___d46));
  module_c_z_mux instance_c_z_mux_7(.c_z_mux_fp(rb_nb3_rb[103]),
				    .c_z_mux_fm(rb_nb3_rb[39]),
				    .c_z_mux_cp(c_z_mux___d46[0]),
				    .c_z_mux(c_z_mux___d48));
  module_c_z_mux instance_c_z_mux_8(.c_z_mux_fp(rb_nb3_rb[104]),
				    .c_z_mux_fm(rb_nb3_rb[40]),
				    .c_z_mux_cp(c_z_mux___d48[0]),
				    .c_z_mux(c_z_mux___d50));
  module_c_z_mux instance_c_z_mux_9(.c_z_mux_fp(rb_nb3_rb[105]),
				    .c_z_mux_fm(rb_nb3_rb[41]),
				    .c_z_mux_cp(c_z_mux___d50[0]),
				    .c_z_mux(c_z_mux___d52));
  module_c_z_mux instance_c_z_mux_10(.c_z_mux_fp(rb_nb3_rb[106]),
				     .c_z_mux_fm(rb_nb3_rb[42]),
				     .c_z_mux_cp(c_z_mux___d52[0]),
				     .c_z_mux(c_z_mux___d54));
  module_c_z_mux instance_c_z_mux_11(.c_z_mux_fp(rb_nb3_rb[107]),
				     .c_z_mux_fm(rb_nb3_rb[43]),
				     .c_z_mux_cp(c_z_mux___d54[0]),
				     .c_z_mux(c_z_mux___d56));
  module_c_z_mux instance_c_z_mux_12(.c_z_mux_fp(rb_nb3_rb[108]),
				     .c_z_mux_fm(rb_nb3_rb[44]),
				     .c_z_mux_cp(c_z_mux___d56[0]),
				     .c_z_mux(c_z_mux___d58));
  module_c_z_mux instance_c_z_mux_13(.c_z_mux_fp(rb_nb3_rb[109]),
				     .c_z_mux_fm(rb_nb3_rb[45]),
				     .c_z_mux_cp(c_z_mux___d58[0]),
				     .c_z_mux(c_z_mux___d60));
  module_c_z_mux instance_c_z_mux_14(.c_z_mux_fp(rb_nb3_rb[110]),
				     .c_z_mux_fm(rb_nb3_rb[46]),
				     .c_z_mux_cp(c_z_mux___d60[0]),
				     .c_z_mux(c_z_mux___d62));
  module_c_z_mux instance_c_z_mux_15(.c_z_mux_fp(rb_nb3_rb[111]),
				     .c_z_mux_fm(rb_nb3_rb[47]),
				     .c_z_mux_cp(c_z_mux___d62[0]),
				     .c_z_mux(c_z_mux___d64));
  assign _theResult___fst__h24 =
	     { c_z_mux___d64[1],
	       c_z_mux___d62[1],
	       c_z_mux___d60[1],
	       c_z_mux___d58[1],
	       c_z_mux___d56[1],
	       c_z_mux___d54[1],
	       c_z_mux___d52[1],
	       c_z_mux___d50[1],
	       c_z_mux___d48[1],
	       c_z_mux___d46[1],
	       c_z_mux___d44[1],
	       c_z_mux___d42[1],
	       c_z_mux___d40[1],
	       c_z_mux___d38[1],
	       c_z_mux___d36[1],
	       c_z_mux___d34[1],
	       rb_nb3_fwd[32:1] } ;
endmodule  // module_rb_nb3

